### ISSUE TITLE
Spawn Rates tweak working when disabled.

### ISSUE THREAD

**Issue by VonSparq** [NoniDOTio/SMPtweaks#6]
I have encountered an issue with the spawn rates tweak, it works even though it is set to false. I came across it while diagnosing why my server has no phantoms, turns out default configuration for the plugin is to set their spawn rates to 0 and the tweak is active even when it is disabled in the config.

```
spawn_rates:
  enabled: false
  mobs:
    - type: CREEPER
      multiplier: 0.7
    - type: PHANTOM
      multiplier: 0
```

Yet no phantoms are spawning, changing the multiplier to 1 while enabled is still false turns their spawns back on.
